spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitness}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081